#!/bin/bash

function showusage {
cat <<EOF

NAME
   ansiblesession - configure and start ansiblesession
   
SYNOPSIS
   ansiblesession init NAME            - Init volumes for session called NAME.
   ansiblesession setcfg NAME CFGFILE  - Update .ansible.cfg with CFGFILE.
   ansiblesession copykeys NAME PATH   - Copy the ssh keys to /root/.ssh/
   
   ansiblesession start NAME           - start ansible session NAME.
   
   ansiblesession nuke NAME            - remove volume containers for NAME.
   ansiblesession list                 - list available ansible sessions.
   
DESCRIPTION
   See https://github.com/j842/docker-ansible for information about the Docker 
   container this script configures and uses.

EXIT VALUES
   0   - success
   1   - error
   3   - no change
   
EOF
   exit 1
}

#------ VARIABLES -------------------

RVAL=3

CONTAINER_SHORTNAME="ansible"
CONTAINER_PREFIX=j842
CONTAINER_NAME="${CONTAINER_PREFIX}/${CONTAINER_SHORTNAME}"

NAME="$2"

VOLUME_NAME="ansible-config-${NAME}"
VOLUME_MOUNT="/config"
VOLUME_VCMD="${VOLUME_NAME}:${VOLUME_MOUNT}"

ANSIBLE_NAME="ansible-data-${NAME}"
# the path that the ansible playbooks are installed in.
# this is also hardcoded in Dockerfile
ANSIBLE_MOUNT="/data"
ANSIBLE_VCMD="${ANSIBLE_NAME}:${ANSIBLE_MOUNT}"

#------------------------------------

function copytocontainer {
   SRCPATH=$1
   DESTPATH=$2
   
   TEMPF="$(mktemp -d)"
   if [ -d ${SRCPATH} ]; then
      # copy folder of stuff
      rsync -a "${SRCPATH}/" "$TEMPF"
   else
      # copy single files
      cp "$SRCFILE" "$TEMPF"
   fi
  
   RESULT=$(docker run -i -t --name=ansible-${NAME} -h ${HOSTNAME}-ansible \
            -v ${VOLUME_VCMD} \
            -v ${ANSIBLE_VCMD} \
           -v ${TEMPF}:/tocopy \
            ${CONTAINER_NAME}  \
            rsync -ai /tocopy/ ${DESTPATH}
            )
   if [ -n "$RESULT" ]; then echo "Files were changed." ; RVAL=0 ; fi
   docker rm ansible-${NAME}
   rm -rf "$TEMPF"
}

function start {
   docker run -i -t --name=ansible-"${NAME}" -h "${HOSTNAME}"-ansible \
            -v "${VOLUME_VCMD}" \
            -v "${ANSIBLE_VCMD}" \
            "${CONTAINER_NAME}"  
            
   docker rm ansible-"${NAME}"
}

function command_exists { command -v "$1" >/dev/null 2>&1 ; }


function ensurevolexists {
  docker volume ls | grep "$1" > /dev/null
  if [ $? -ne 0 ] ; then
     echo Creating volume "$1"
     docker volume create --name "$1"
     RVAL=0
  fi
}

#   ansiblesession init NAME            - Init volumes for session called NAME.
function init {
   ensurevolexists "${VOLUME_NAME}"
   ensurevolexists "${ANSIBLE_NAME}"   
   
   rm -rf /tmp/config ; mkdir /tmp/config
cat <<EOF >/tmp/config/ansible.cfg
[defaults]
host_key_checking = false
pipelining = true
EOF
   mkdir /tmp/config/sshkeys
   
   copytocontainer /tmp/config /config
}

function namelist {
   NAMELIST=$(docker volume ls | grep ansible-config- | sed s/^.*config-//)
}


case "$1" in
   init)
      if [ -z "$NAME" ]; then showusage ; fi
      init
      ;;
      
   setcfg)
      if [ -z "$NAME" ]; then showusage ; fi
      setcfg "$3"
      ;;
      
   copykeys)
      if [ -z "$NAME" ]; then showusage ; fi
      copykeys "$3"
      ;;
      
   start)
      if [ -z "$NAME" ]; then showusage ; fi
      start
      ;;
      
   nuke)
      if [ -z "$NAME" ]; then showusage ; fi
      docker volume rm "$VOLUME_NAME"
      docker volume rm "$ANSIBLE_NAME"
      ;;
      
   clean)
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc
      ;;
      
   list)
      namelist
      echo "$NAMELIST"
      ;;
      
   *)
      showusage
      ;;
esac

#FNAME=$(basename $BASH_SOURCE) 

