#!/bin/bash

function sayinfo { echo -e "[ \e[2m${1}\e[0m ]" ; }
function saygood { echo -e "[ \e[32m${1}\e[0m ]" ; }
function saybad { echo -e "[ \e[31m\e[1m${1}\e[0m ]" ; }


function pushy {
  ( #subshell
  cd "/root/dev/$1"
  BRANCH=$(git rev-parse --abbrev-ref HEAD) || BRANCH="wibble"
  [ "$BRANCH" = "dev" ] || { sayinfo "On $BRANCH not dev: $d" ; exit 0 ; }
  [ -e "push" ] || { sayinfo "Doesn't have push script: $D" ; exit 0 ; }
  ./push || { saybad "FAILED for $1" ; exit 1 ; }
  saygood "Pushed $d to $BRANCH"
  )
}

for d in */ ; do
    pushy "$d"
done
